apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 6Gi
  hostPath:
    path: /volume_jenkins/              # Volume mapeado pelo kind.yaml em containerPath.